coodepool/coodepool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vendingMashine.urls')),
    path('', RedirectView.as_view(url='index/'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

coodepool/vendingMashine/urls.py
from django.urls import path
from . import views

app_name = 'vendingMashine'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('add-product/', views.addNewProduct, name='add-product'),
    path('user-products/', views.getUserProducts, name='user-products'),
    path('user-products-update/<int:pk>/', views.updateForm, name='user-products-update'),
    path('user-products-delete/<int:pk>/', views.deleteProduct, name='user-products-delete'),
    path('set-deposit/', views.setNewDeposit, name='set-deposit'),
    path('withdraw-deposit/<int:pk>/', views.withdrawDEposit, name='withdraw-deposit'),
    path('all-products/', views.allProducts, name='all-products'),
    path('get-products-data/<int:pk>', views.insertProductForm, name='get-products-data'),
    path('buy-product/<int:pk>', views.buyProducts, name='buy-product'),
    path('all-purchases/', views.allPurchases, name='all-purchases'),
    path('all-products-xhr/', views.showAllProducts, name='all-products-xhr'),
    path('registration/', views.registration, name='registration'),

]

coodepool/vendingMashine/forms.py
from django import forms
from .models import Products, Korisnik, Deposit, BuyProduct
from django.core.exceptions import ValidationError
from django.forms.widgets import HiddenInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model







class CreateUserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2', 'role', 'deposit']
        # exclude = ['is_active']


    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['deposit'].widget.attrs['readonly'] = True


class MyForm(forms.ModelForm):

    class Meta:
        model = Products
        fields = '__all__'
        widgets = {'user_product': forms.HiddenInput()}

    def clean(self):
        username = self.cleaned_data['user_product']
        amount = self.cleaned_data['amountAvailable']
        cost = self.cleaned_data['cost']
        prductName = self.cleaned_data['productName']
        user = Korisnik.objects.get(username=username.username)

        if user.role == 'buyer':
            raise ValidationError('You can not enter new products as buyer role')
        if amount < 0:
            raise ValidationError("Entered product's amount is less than 0")
        if cost < 0:
            raise ValidationError("Entered product's cost is less than 0")
        if prductName == None:
            raise ValidationError("Entered fild for product name is empty")

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(MyForm, self).__init__(*args, **kwargs)
        # self.fields['user_product'].widget = HiddenInput()

class SetDepositForm(forms.ModelForm):

    class Meta:
        model = Deposit
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(SetDepositForm, self).__init__(*args, **kwargs)


class BuyProductForm(forms.ModelForm):
    class Meta:
        model = BuyProduct
        fields = '__all__'


    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(BuyProductForm, self).__init__(*args, **kwargs)

    def clean(self):
        username = self.cleaned_data['user_buy']
        formProduct = self.cleaned_data['product_name']
        amountForm = self.cleaned_data['amount']
        user = Korisnik.objects.get(username=username.username)
        product = Products.objects.get(id=formProduct.pk)
        amount = product.amountAvailable - amountForm
        wholePrice = product.cost * amountForm
        checkBuyerDeposite = username.deposit
        if checkBuyerDeposite < wholePrice:
            raise ValidationError('You do not have enough money on your deposit to buy this product.')
        print(amount)
        if product.amountAvailable < amountForm:
            raise ValidationError('You entered product amount to buy higher than amount available')
        if amountForm < 0:
            raise ValidationError('You entered product amount to buy less than zero')
        if user.role == 'seller':
            raise ValidationError('You can not buy products as seller role')


# update product form
class ProductsUpdateForm(forms.ModelForm):

    class Meta:
        model = Products
        fields = '__all__'
        exclude = ['user_product']
        widgets = {
                   'cost': forms.TextInput(attrs={'id':'cost', 'name': 'newcost'}),
                   'amountAvailable': forms.TextInput(attrs={'id':'amount', 'name':'amount'}),
                   'productName': forms.TextInput(attrs={'id':'name', 'name':'name'})}



class BuyProductFormData(forms.ModelForm):
    class Meta:
        model = BuyProduct
        fields = '__all__'
        exclude = ['user_buy', 'product_name']

coodepool/vendingMashine/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.http import JsonResponse, HttpResponse





def index(request):

    user = request.user
    context = {}
    try:
        currentUser = Korisnik.objects.get(id=user.pk)
        idCurrentUser = currentUser.pk
        context['currentUser'] = currentUser
        context['idCurrentUser'] = idCurrentUser

        purchasesAll = BuyProduct.objects.filter(user_buy__username=user.username)
        context['purchases'] = purchasesAll
    except Korisnik.DoesNotExist:
        comment = None
    form = MyForm(request.POST or None, initial={'user_product': request.user})
    formUpdate = ProductsUpdateForm(request.POST or None)
    formDeposit = SetDepositForm(request.POST or None, initial={'user_deposit': request.user})

    context['user'] = user
    context['form'] = form
    context['formUpdate'] = formUpdate
    context['formDeposit'] = formDeposit

    return render(request, 'vendingMashine/index.html', context)


def addNewProduct(request):
    form = MyForm(request.POST or None)
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        validate = form.save(commit=False)
        name = validate.productName
        user = request.user
        if int(validate.amountAvailable) < 0:
            return JsonResponse({'error':'You entered amount of products less than 0'})
        if Products.objects.filter(productName=name, user_product__username=user.username):
            return JsonResponse({'error': 'You have this item in your shop.'})
        else:
            validate.save()
        return JsonResponse({'message': 'You created new product successfully!'})
    return JsonResponse({'error':'You did not created new product'})


def getUserProducts(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        user = request.user
        userData = Korisnik.objects.get(username=user.username)

        username = userData.username
        products = Products.objects.filter(user_product__username=userData.username).values().order_by('productName')
        dictOfProducts = []
        for product in products:
            dictOfProducts.append(product)
        return JsonResponse({'data':dictOfProducts, 'username':username})
    return render(request, 'vendingMashine/copy.html', {})

def updateForm(request, pk=None):

    product = Products.objects.get(id=pk)

    # updateInstance = model_to_dict(product)
    form = ProductsUpdateForm(request.POST or None)
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        cost = request.POST.get('cost')
        amount = request.POST.get('amount')
        product.amountAvailable = amount
        product.cost = cost
        product.user_product = request.user
        product.save()
        return JsonResponse({'update':'Product has been updated'})

    return JsonResponse({'error': 'Product has not been updated'})

def deleteProduct(request, pk=None):
    product = Products.objects.get(id=pk)
    name = product.productName
    if request.method == 'DELETE':
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            product.delete()
            return JsonResponse({'update': f'Product {name} has been deleted'})

    return JsonResponse({'error': 'Product has not been deleted'})

def setNewDeposit(request):
    user = request.user

    form = SetDepositForm(request.POST or None)
    if request.method == 'POST':
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            depo = form.save(commit=False)
            deposit = depo.add_deposit
            depo.save()
            if user:
                userId = Korisnik.objects.get(id=user.pk)
                fullDeposit = userId.deposit
                return JsonResponse({'message': f'You set new deposit {deposit} successfully!', 'newDeposit':fullDeposit})
            else:
                return JsonResponse({'message': f'You set new deposit {deposit} successfully!', 'newDeposit': 0})
    return JsonResponse({'error': 'You did not set deposit'})

def withdrawDEposit(request, pk=None):
    user = Korisnik.objects.get(id=pk)
    if request.method == 'PUT':
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            withdraw_deposit = user.deposit
            user.deposit = 0
            user.save()
            from .helper import set_coins

            listOfCoins1 = [5, 10, 20, 50, 100]
            dictOfCoinsAmount = {}
            deposit = withdraw_deposit
            set_coins(deposit, listOfCoins1, dictOfCoinsAmount)
            print(withdraw_deposit)

            return JsonResponse({'message':'Your deposit is 0', 'coins':dictOfCoinsAmount})
    return JsonResponse({'error': 'You did not withdraw deposit'})


def allProducts(request):
    products = Products.objects.all()
    form = BuyProductFormData(request.POST or None)
    context = {
        'products': products,
        'form': form
    }
    user = request.user
    return render(request, 'vendingMashine/buy_products.html', context)

def buyProducts(request, pk=None):
    if request.method == 'POST':
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            try:
                amount = request.POST.get('amount')

                product = Products.objects.filter(productName__isnull=False)
                for p in product:
                    if p.pk == pk:


                        wholePrice = int(p.cost) * int(amount)
                        pro = Products.objects.get(id=p.pk)
                        proAmount = int(pro.amountAvailable) - int(amount)
                        user = request.user
                        userQuery = Korisnik.objects.get(id=user.pk)
                        userDeposit = userQuery.deposit
                        if int(wholePrice) > int(userDeposit):
                            return JsonResponse({'error': 'You have no enough money on you deposit account to buy this product'})
                        if int(p.amountAvailable) < int(amount):
                            return JsonResponse({'error': 'Requested amount of product is higher than in stock. Please order less amount. '})
                        if userQuery.role == 'seller':
                            return JsonResponse({'error': 'You can not buy items as seller role.'})

                        else:
                            buyProduct = BuyProduct.objects.create(product_name=p, user_buy=request.user, amount=p.cost,
                                                                   cost=wholePrice)
                            buyProduct.save()
                            newDeposit = int(userDeposit) - int(wholePrice)
                            userQuery.deposit = newDeposit
                            userQuery.save()
                            userNew = request.user
                            userQueryNew = Korisnik.objects.get(id=userNew.pk)
                            userDepositNew = userQueryNew.deposit
                            pro.amountAvailable = proAmount
                            pro.save()


                            return JsonResponse({'message': 'You purchase was successfull!', 'newDeposit': userDepositNew, 'productName': p.productName,
                                                 'amountAvailable':proAmount, 'cost':p.cost, 'pk':p.pk})

            except Korisnik.DoesNotExist:
                user = None


    return JsonResponse({'error': 'Some error occured. Try again.'})

def insertProductForm(request, pk=None):
    context = {}
    product = ''
    try:
        user = request.user
        product = Products.objects.filter(productName__isnull=False)
        for p in product:
            if p.pk == pk:
                context['productName'] = p.productName
                context['amountAvailable'] = p.amountAvailable
                context['cost'] = p.cost
                context['pk'] = p.pk
    except Korisnik.DoesNotExist:
        user = None
    print(context)

    return JsonResponse(context)

def allPurchases(request):
    user = request.user
    try:
        user = Korisnik.objects.get(id=user.pk)
        context = {}
        purchasesAll = BuyProduct.objects.filter(user_buy__username=user.username)
        for purch in purchasesAll:
            context['id'] = purch.pk
            context['product_name'] = purch.product_name.productName
            context['user_buy'] = purch.user_buy.username
            context['amount'] = purch.amount

        return JsonResponse(context)


    except Korisnik.DoesNotExist:
        user = None

    return render(request, 'vendingMashine/copy.html', {})

def showAllProducts(request):
    context = {}
    product = Products.objects.all().values('id','user_product__username', 'amountAvailable', 'cost', 'productName')
    counter = 0
    for p in product:
        context[f'product_{counter}'] = [p]
        counter = counter + 1
    return JsonResponse(context)

def registration(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('/index/')
    else:
        form = CreateUserForm()

    return render(request, 'vendingMashine/registration_form.html', {'form':form})


from django.contrib.auth.models import User

coodepool/vendingMashine/templates/vendingMashine/buy_products.html
{% extends 'vendingMashine/products.html' %}
{% load static %}
  {% load crispy_forms_tags %}
{% block products %}

    {#    modal #}
    <div class="modal" tabindex="-1" role="dialog" id="myModalBuy">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Buy this product</h5>
        <button type="button" class="close3" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-left">
        <h5 id="error-text1" class="text-warning"></h5>
          <h5 id="success-text1"></h5>

            {#  form part   #}
          <div class="container-fluid" id="updateFormModal">
              <h4 id="insertProductName" class="text-secondary"></h4>
              <p id="pk" style="display: none"></p>
              <form method="post" id="formBuy">
                  {% csrf_token %}

                        <div class="form-group mb-0">
                            {{ form.amount|as_crispy_field }}
                        </div>

                    <button type="submit" class="btn btn-primary align-self-start mb-4" id="buyProductButton">Buy product</button>
                </form>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary close4" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{#  modal end #}
    {% if products %}
        {% if idCurrentUser %}<p id="getUserIdBuy" style="display: none">{{ idCurrentUser }}</p>{% endif %}

    <div class="container">
    <h4 class="text-success">All products</h4>
    <div class="container-fluid d-md-flex flex-row flex-lg-start flex-md-wrap overflow-auto" id="addPurchases" style="height: calc(100vh - 215px)">
        {% for product in products %}
            <div class="container text-left border border-secondary rounded mb-2 align-items-start buyProductClass overflow-auto" style="width: 17rem; height:20rem">
            <p class="getProductId" style="display: none">{{ product.pk }}</p>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">Product name: {{ product.productName }}</li>
                  <li class="list-group-item">Seller: {{ product.user_product.username }}</li>
                  <li class="list-group-item">Amount available: {{ product.amountAvailable }}</li>
                  <li class="list-group-item">Cost: {{ product.cost }}</li>
            </ul>
            </div>



        {% endfor %}





    </div>
        </div>

{% endif %}
    <script src="{% static 'js/buyProductSCript.js' %}"></script>
{% endblock %}

coodepool/vendingMashine/templates/vendingMashine/index.html
{% extends 'vendingMashine/products.html' %}
{% load static %}
  {% load crispy_forms_tags %}
{% block seller_buyer %}
{% if idCurrentUser %}<p id="getUserId" style="display: none">{{ idCurrentUser }}</p>{% endif %}
{#    modal #}
    <div class="modal" tabindex="-1" role="dialog" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New product inserted by {{ user.username }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-left">
        <h5 id="error-text" class="text-warning"></h5>
          <h5 id="success-text"></h5>
          <div class="container-fluid" id="available-dates"></div>
            {#  form part   #}
          <div class="container-fluid" id="updateFormModal">
              <form method="post" id="formUpdateProduct">
                {% csrf_token %}

                        <div class="form-group mb-0">
                            {{ formUpdate.productName|as_crispy_field }}
                        </div>


                        <div class="form-group mb-0">
                             {{formUpdate.amountAvailable|as_crispy_field }}
                        </div>


                        <div class="form-group mb-0">
                            {{ formUpdate.cost|as_crispy_field }}
                        </div>

                    <button type="submit" class="btn btn-primary align-self-start mb-4" id="updateProduct">Submit</button>
                </form>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary close2" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{#  modal end #}

{#        seller form ad functions  #}
    {% if currentUser.role == 'seller' %}

        <div class="row text-left pl-4 pr-4">
                    <p id="hiddenProdutct" style="display: none">1</p>

            <div class="col-lg-4 border border-secondary rounded mb-4">
                    <h5>Enter new product</h5>
             <form method="post" id="formAddProduct">
                {% csrf_token %}
                         <div class="form-group mb-0">
                            {{ form.user_product|as_crispy_field }}
                        </div>
                        <div class="form-group mb-0">
                            {{ form.productName|as_crispy_field }}
                        </div>


                        <div class="form-group mb-0">
                             {{form.amountAvailable|as_crispy_field }}
                        </div>


                        <div class="form-group mb-0">
                            {{ form.cost|as_crispy_field }}
                        </div>

                    <button type="submit" class="btn btn-primary align-self-start mb-4" id="submitProduct">Submit</button>
                </form>
            </div>
            <div class="col-lg-7 border border-secondary rounded mb-4 offset-lg-1">
                <h4 class="text-primary">All produkts of user <span class="text-danger">{{ user.username }}</span></h4>
                <div class="container-fluid overflow-auto border border-secondary rounded mb-4" style="height: 25rem">
                    <ul class="list-group list-group-flush" id="loopUserProducts">

                    </ul>
                </div>
            </div>
        </div>
        {% else %}
{#  deposit form      #}
    <div class="row">
        <div class="col-lg-3 offset-lg-2 text-left">
            <p id="hiddenProdutct" style="display: none">2</p>
            <h4 class="text-success">Insert new deposit</h4>
            <div class="container-fluid border border-secondary rounded mb-4 p-2">

                    <form method="post" id="formInsertDeposit">
                {% csrf_token %}

                        <div class="form-group mb-0">
                            {{ formDeposit.user_deposit|as_crispy_field }}
                        </div>


                        <div class="form-group mb-0">
                             {{formDeposit.add_deposit|as_crispy_field }}
                        </div>

                    <button type="submit" class="btn btn-primary align-self-start mb-4" id="setNewDepButton">Submit</button>
                </form>
            </div>
        {#  end deposit form part   #}

        {#  withdraw deposit part   #}
        <div class="container border border-secondary rounded mb-4">
            <h4 class="text-danger pt-2">Withdraw deposit <button type="button" class="btn btn-outline-primary btn-sm" id="resetDeposit">RESET</button></h4>
            <div class="container overflow-auto p-2 border border-secondary rounded mb-4" style="height: 14rem">
                <ul class="list-group" id="list-group">


                </ul>
            </div>

        </div>
        </div>
        <div class="col-lg-6 offset-lg-1 text-left">
            <h4 class="text-success">All purchases by {{ user.username }}</h4>
                <div class="container text-left overflow-auto p-2 border border-secondary rounded" style="height: 25rem">
                    <ul class="list-group list-group-flush">
                        {% for purch in purchases %}
                            <li class="list-group-item">Product: {{ purch.product_name.productName }} amount: {{ purch.amount }} cost: {{ purch.cost }} coins</li>
                        {% endfor %}
                    </ul>
                </div>
        </div>
    </div>
{# end of deposit form#}
{% endif %}
    <script src="{% static 'js/addProductScript.js' %}"></script>
    <script src="{% static 'js/allUsersProducts.js' %}"></script>
    <script src="{% static 'js/setNewDeposit.js' %}"></script>
    <script src="{% static 'js/withdrawDeposit.js' %}"></script>
{% endblock %}

coodepool/vendingMashine/templates/vendingMashine/products.html
<!doctype html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>VENDING MASHINE</title>
  </head>
  <body>
  {% load crispy_forms_tags %}

<nav class="navbar navbar-expand-md navbar-light bg-light fixed-top mb-5">
    <a href="" class="navbar-brand ml-5">VENDING MASHINE</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#myNavbar1">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="myNavbar1">
        <ul class="navbar-nav">
        <li class="nav-item">
                <a href="{% url 'vendingMashine:all-products' %}" class="nav-link active">Products</a>
            </li>
            <li class="nav-item">

                {% if user.is_authenticated %}

                <a href="{% url 'vendingMashine:index' %}" class="nav-link active">{% if 'buyer' == user.role %}Buyer{% else %}Seller{% endif %}</a>


                {% endif %}
            </li>

            <li class="nav-item">
                {% if user.is_authenticated %}
                    {% if user.is_admin %}
                     <a href="{% url 'admin:index' %}" class="nav-link">API</a>
                        {% endif %}
                {% endif %}
            </li>
        <li class="nav-item user-loged">
            {% if user.is_active %}
                <p>Currently loged in: <span class="text-success">{{ user.username }}</span> Deposit: <span class="text-danger" id="navBarDeposit">{{ user.deposit }} coins</span></p>
                        {% endif %}
        </li>
        </ul>
{#                <div class="d-none d-md-block seperator navbar-text pb-3 ml-2">|</div>#}
     <ul class="navbar-nav">
                 {% if user.is_authenticated %}
                     <li class="nav-item">
                    <a class="nav-link pb-3" href="{% url 'logout' %}?next={{ request.path }}" style="color: #ff6f00">Log out</a>
                     </li>
                {% else %}
                     <li class="nav-item">
                    <a id="link-login" class="nav-link" href="{% url 'login' %}?next={{ request.path }}" style="color: #999999">Log in</a>
                     </li>
                     <li class="nav-item">
                     <a class="nav-link pb-2" href="{% url 'vendingMashine:registration' %}" style="color: #999999">Register</a>
                     </li>
                {% endif %}
     </ul>

    </div>
</nav>


<div class="container-fluid text-center">
    <h4 class="display-4 text-success" style="margin-top: 5rem">VENDING MASHINE</h4>
{% if user.is_authenticated %}
    {% block seller_buyer %}{% endblock %}
{% endif %}
    {% block products %}{% endblock %}
    {% block login %}{% endblock %}
    {% block logout %}{% endblock %}
    {% block registration %}{% endblock %}

</div>





    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/moment.min.js"></script>


  </body>
</html>

coodepool/vendingMashine/templates/vendingMashine/registration_form.html
{% extends 'vendingMashine/products.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block registration %}
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <hr class="mt-0 mb-4">

      <h4 class="text-success">Create your account</h4>

            <div class="container-fluid text-left border border-secondary rounded" style="width: 30rem">
              <form method="post">
                {% csrf_token %}


                        <div class="form-group mb-0">
                            {{ form.username|as_crispy_field }}
                        </div>


                        <div class="form-group mb-0">
                             {{form.password1|as_crispy_field }}
                        </div>
                         <div class="form-group mb-0">
                             {{form.password2|as_crispy_field }}
                        </div>


                        <div class="form-group mb-0">
                            {{ form.role|as_crispy_field }}
                        </div>
                   <div class="form-group mb-0">
                            {{ form.deposit|as_crispy_field }}
                        </div>

                    <button type="submit" class="btn btn-primary align-self-start mb-4">Sign In</button>
                </form>
          </div>


            </div>
            </div>
                  </div>
{% endblock %}